### ISSUE TITLE
Tat mark of the hero, mark of intellect 

### ISSUE THREAD

**Issue by lordbogit** [SWG-Source/dsrc#162]
the spawner in mos epsa is not desporning all the npc's stoping the next one form spawning
![markofthehero](https://user-images.githubusercontent.com/353448/99381584-35b94480-28c3-11eb-875a-6356082ecaa3.png)

**Comment by lordbogit** [comment]
i have just checked the server box there is an error showing as shown below
![markofthehero2](https://user-images.githubusercontent.com/353448/99384303-1e7c5600-28c7-11eb-948a-f0f2ccdc1278.png)

**Comment by TyroneSWG** [comment]
I remember this happening back on Reborn. going to try to reproduce.

**Comment by TyroneSWG** [comment]
`    (cda2d192): Unable to find default weapon slot id for 19000334(object/creature/player/zabrak_male.iff)
ERROR calling dictionary.put(Object, String): null value
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:1387)
	at script.dictionary.put(dictionary.java:397)
	at script.library.money.requestPayment(money.java:348)
	at script.conversation.quest_hero_of_tatooine_farmer.quest_hero_of_tatooine_farmer_action_paid_ransom(quest_hero_of_tatooine_farmer.java:98)
	at script.conversation.quest_hero_of_tatooine_farmer.quest_hero_of_tatooine_farmer_handleBranch16(quest_hero_of_tatooine_farmer.java:1321)
	at script.conversation.quest_hero_of_tatooine_farmer.OnNpcConversationResponse(quest_hero_of_tatooine_farmer.java:2142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at script.script_entry.runScript(script_entry.java:434)
	at script.script_entry.runScripts(script_entry.java:639)
ERROR calling dictionary.put(Object, String): null value
java.lang.Exception: Stack trace
	at java.base/java.lang.Thread.dumpStack(Thread.java:1387)
	at script.dictionary.put(dictionary.java:397)
	at script.library.money.pay(money.java:452)
	at script.player.player_money.handlePaymentRequest(player_money.java:358)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at script.script_entry.callMessageHandler(script_entry.java:745)
	at script.script_entry.callMessageHandlers(script_entry.java:954)
	at script.script_entry.callMessageHandlers(script_entry.java:875)

`
When paying the 10000 ransom. not sure if this is related to the spawning issue though.

**Comment by lordbogit** [comment]
its all the same mission

**Comment by AconiteGodOfSWG** [comment]
This should be fixed via 9102dd4. Based on the [information on SWG Wikia](https://swg.fandom.com/wiki/Hero_of_Tatooine#The_Mark_of_Intellect), the group of mobs should de-spawn whether you fail or succeed in answering the who is a liar prompt, which is what is set to happen now. Please let me know if this functionality needs further adjustment. Thanks!
